In [1]:
import numpy as np

## Scalar

In [2]:
s = 5
s

5

## Vector

In [3]:
v = np.array([5,-2,4])
v

array([ 5, -2,  4])

## Matrices

In [4]:
m = np.array([[5 ,12 ,6], [-3 ,0 , 14]])
m

array([[ 5, 12,  6],
       [-3,  0, 14]])

## Data Types

In [5]:
type(s)

int

In [6]:
type(v) # 1D array

numpy.ndarray

In [7]:
type(m) # 2D array

numpy.ndarray

we can also declare 's' as ndarray

In [8]:
s_array = np.array(5)

In [9]:
s_array

array(5)

In [10]:
type(s_array)

numpy.ndarray

## Data Shapes

In [11]:
m.shape

(2, 3)

In [12]:
v.shape

(3,)

In [13]:
v.reshape(1,3)

array([[ 5, -2,  4]])

In [14]:
v.reshape(3,1)

array([[ 5],
       [-2],
       [ 4]])

In [15]:
s.shape 

AttributeError: 'int' object has no attribute 'shape'

In [16]:
s_array.shape # scalars are 0 dimensional objects so they don't have shapes.

()

## Addition and Subtraction of Matrices

In [17]:
m1 = np.array([[5,12,6],[-3,0,14]])
m1

array([[ 5, 12,  6],
       [-3,  0, 14]])

In [18]:
m2 = np.array([[9,8,7],[1,3,-5]])
m2

array([[ 9,  8,  7],
       [ 1,  3, -5]])

In [19]:
m1 + m2

array([[14, 20, 13],
       [-2,  3,  9]])

In [20]:
m3 = np.array([[5,3],[-2,4]])
m3

array([[ 5,  3],
       [-2,  4]])

In [21]:
m4 = np.array([[7,-5],[3,8]])
m4

array([[ 7, -5],
       [ 3,  8]])

In [22]:
m3 - m4

array([[-2,  8],
       [-5, -4]])

In [23]:
m1 + m3

ValueError: operands could not be broadcast together with shapes (2,3) (2,2) 

**in order to add vectors and matrices, their forms must match, we aren't allowed to add vectors of different length and matrices of different dimensions.**

### Addition of Vectors

In [24]:
v1 = np.array([1,2,3,4,5])

In [25]:
v2 = np.array([5,4,3,2,1])

In [26]:
v1 + v2

array([6, 6, 6, 6, 6])

In [27]:
v1 - v2

array([-4, -2,  0,  2,  4])

In [28]:
v3 = np.array([1,2,3])
v3

array([1, 2, 3])

In [29]:
v1 + v3

ValueError: operands could not be broadcast together with shapes (5,) (3,) 

### Addition of Scalars

In [30]:
5 + 5 

10

In [31]:
10 - 5

5

we can add scalar to matrices and vectors

In [32]:
m1

array([[ 5, 12,  6],
       [-3,  0, 14]])

In [33]:
m1 + 1

array([[ 6, 13,  7],
       [-2,  1, 15]])

In [34]:
m1 + np.array([1])

array([[ 6, 13,  7],
       [-2,  1, 15]])

In [35]:
v1 

array([1, 2, 3, 4, 5])

In [36]:
v1 + 1

array([2, 3, 4, 5, 6])

In [37]:
v1 + np.array([1])

array([2, 3, 4, 5, 6])

**Mathematically, these operations are not allowed as the shapes are differnet but it works in Python, reason being this result has a meaning in terms of arrays, but not in terms of linear algebra**

## Transposing Vectors and Matrices

    The values are not changing or transforming, only their position is.

    Transposing the same vector twice yields the initial vector.

    a 3x1 matrix transposed is 1x3 matrix

### Transposing Matrices

In [38]:
A = np.array([[5,12,6],[-3,0,14]])
A

array([[ 5, 12,  6],
       [-3,  0, 14]])

In [39]:
A.T

array([[ 5, -3],
       [12,  0],
       [ 6, 14]])

In [40]:
B = np.array([[5,3],[-2,4]])
B

array([[ 5,  3],
       [-2,  4]])

In [41]:
B.T

array([[ 5, -2],
       [ 3,  4]])

In [42]:
C = np.array([[4,-5],[8,12],[-2,-3],[19,0]])
C

array([[ 4, -5],
       [ 8, 12],
       [-2, -3],
       [19,  0]])

In [43]:
C.T

array([[ 4,  8, -2, 19],
       [-5, 12, -3,  0]])

### Transposing Scalars and Vectors

### Transposing Scalars

In [44]:
s = np.array([5])

In [45]:
s.T

array([5])

Transpose of a scalar is itself

### Transposing Vectors

In [46]:
x = np.array([1,2,3])
x

array([1, 2, 3])

In [47]:
x.T

array([1, 2, 3])

This is because, in Python, 1D array don't really get transposed

But, you can transpose it by reshaping it.

In [48]:
x.shape

(3,)

In [49]:
x_shaped = x.reshape(1,3)
x_shaped

array([[1, 2, 3]])

In [50]:
x_shaped.T

array([[1],
       [2],
       [3]])

## Multiplication (or) Dot Product of Vectors

In [51]:
x = np.array([2,8,-4])
y = np.array([1,-7,3])

In [52]:
np.dot(x,y)

-66

In [53]:
a = np.array([0,2,5,8])
b = np.array([20,3,4,-1])

In [54]:
np.dot(a,b)

18

### Scalar * Scalar

In [55]:
np.dot(5,8)

40

In [56]:
np.dot(10,-4)

-40

### Scalar * Vector

In [57]:
x

array([ 2,  8, -4])

In [58]:
5 * x

array([ 10,  40, -20])

## Dot Product of Matrices

### Scalar * Matrix

In [59]:
A = np.array([[5,12,6],[-3,0,14]])
A

array([[ 5, 12,  6],
       [-3,  0, 14]])

In [60]:
3 * A

array([[15, 36, 18],
       [-9,  0, 42]])

### Matrix * Matrix

In [61]:
B = np.array([[2,-1],[8,0],[3,0]])
B

array([[ 2, -1],
       [ 8,  0],
       [ 3,  0]])

In [62]:
np.dot(A,B)

array([[124,  -5],
       [ 36,   3]])

In [63]:
C = np.array([[-12,5,-5,1,6],[6,-2,0,0,-3],[10,2,0,8,0],[9,-4,8,3,-6]])
C

array([[-12,   5,  -5,   1,   6],
       [  6,  -2,   0,   0,  -3],
       [ 10,   2,   0,   8,   0],
       [  9,  -4,   8,   3,  -6]])

In [64]:
D = np.array([[6,-1],[8,-4],[2,-2],[7,4],[-6,-9]])
D

array([[ 6, -1],
       [ 8, -4],
       [ 2, -2],
       [ 7,  4],
       [-6, -9]])

In [65]:
np.dot(C,D)

array([[-71, -48],
       [ 38,  29],
       [132,  14],
       [ 95,  57]])